### ISSUE TITLE
Feature request: If subject contains "CVE" add security@gentoo.org

### ISSUE THREAD

**Issue by jonasstein** [mgorny/bug-assign-user-js#5]
Feature request: If the subject contains "CVE" add security@gentoo.org to the list.

**Comment by mgorny** [comment]
Actually, i had something else in mind: having a static list of additional common people of interest: qa, security, licenses…

**Comment by jonasstein** [comment]
A permanent list with these candidates would be very handy too. Perhaps we can just add these to the array?

**Comment by mgorny** [comment]
Solved via #8.
